apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuelokbt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuelokbt
  template:
    metadata:
      labels:
        app: vuelokbt
    spec:
      containers:
        - name: vuelokbt-app
          image: vuelokbt-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/vuelokbt
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: vuelokbt-service
spec:
  type: LoadBalancer
  selector:
    app: vuelokbt
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP